[pytest]
minversion = 6.0
addopts = -ra -q
norecursedirs = .git venv build dist
xfail_strict = true

# Treat warnings as errors, but ignore DeprecationWarnings
filterwarnings =
    error
    ignore::DeprecationWarning

# Django integration
DJANGO_SETTINGS_MODULE = vox_api.settings

# Test file discovery patterns
python_files = tests.py test_*.py *_tests.py
