# Redis configuration
import os
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from vox_api.aws_secrets import get_aws_secret

REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = int(os.environ.get("REDIS_PORT", 6379))
REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"

# Logging configuration


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "accounts.email": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Email settings
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

# Frontend URL for password reset links
FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://your-frontend")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
    "ALLOWED_VERSIONS": ["v1", "v2"],
    "VERSION_PARAM": "version",
    "DEFAULT_VERSION": "v1",
    # Throttling for scalability
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "1000/day",
        "anon": "100/day",
    },
    # Pagination for large lists
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Custom exception handler for unified error responses
    "EXCEPTION_HANDLER": "vox_api.utils.custom_exception_handler",
}
"""
Django settings for vox_api project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


DATABASE_URL = os.environ.get("DATABASE_URL")


def _database_config_from_url(url: str) -> dict:
    parsed = urlparse(url)
    scheme = parsed.scheme
    if "+" in scheme:
        scheme = scheme.split("+", 1)[0]
    scheme = scheme.replace("postgresql", "postgres")
    if not scheme.startswith("postgres"):
        raise ValueError(f"Unsupported database backend '{parsed.scheme}'.")

    query_params = {key: values[-1] for key, values in parse_qs(parsed.query).items()}

    config: dict[str, object] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parsed.path.lstrip("/") or "postgres",
        "USER": parsed.username or "",
        "PASSWORD": parsed.password or "",
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or "5432"),
    }
    if query_params:
        config["OPTIONS"] = query_params
    return config


if os.environ.get("DJANGO_ENV") == "production":
    # Load secrets from AWS Secrets Manager
    secret_config = get_aws_secret(
        os.environ.get("DJANGO_AWS_SECRET_NAME", "vox-api-config")
    )
    SECRET_KEY = secret_config.get("DJANGO_SECRET_KEY")
    database_url = secret_config.get("DATABASE_URL")
    POSTGRES_DB = secret_config.get("POSTGRES_DB")
    POSTGRES_USER = secret_config.get("POSTGRES_USER")
    POSTGRES_PASSWORD = secret_config.get("POSTGRES_PASSWORD")
    POSTGRES_HOST = secret_config.get("POSTGRES_HOST", "db")
    POSTGRES_PORT = secret_config.get("POSTGRES_PORT", "5432")
    AWS_STORAGE_BUCKET_NAME = secret_config.get("AWS_STORAGE_BUCKET_NAME", "")
    AWS_ACCESS_KEY_ID = secret_config.get("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = secret_config.get("AWS_SECRET_ACCESS_KEY", "")
    AWS_S3_REGION_NAME = secret_config.get("AWS_S3_REGION_NAME", "us-east-1")
    STRIPE_SECRET_KEY = secret_config.get("STRIPE_SECRET_KEY") or os.environ.get(
        "STRIPE_SECRET_KEY",
        "",
    )
    STRIPE_WEBHOOK_SECRET = secret_config.get(
        "STRIPE_WEBHOOK_SECRET"
    ) or os.environ.get(
        "STRIPE_WEBHOOK_SECRET",
        "",
    )
    if database_url:
        DATABASE_URL = database_url
else:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-change-me")

    STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "sk_test_your_default_key")
    STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")

# Set DEBUG based on DJANGO_ENV
DJANGO_ENV = os.environ.get("DJANGO_ENV", "development")
DEBUG = DJANGO_ENV == "development"

use_redis_pref = os.environ.get("USE_REDIS_FOR_CELERY")
if use_redis_pref is None:
    USE_REDIS_FOR_CELERY = not DEBUG
else:
    USE_REDIS_FOR_CELERY = use_redis_pref == "1"

celery_broker = os.environ.get("CELERY_BROKER_URL")
celery_backend = os.environ.get("CELERY_RESULT_BACKEND")

if USE_REDIS_FOR_CELERY and not celery_broker:
    celery_broker = REDIS_URL
if USE_REDIS_FOR_CELERY and not celery_backend:
    celery_backend = REDIS_URL

CELERY_BROKER_URL = celery_broker or "memory://"

if celery_backend:
    CELERY_RESULT_BACKEND = celery_backend
elif CELERY_BROKER_URL.startswith("redis://"):
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL
else:
    CELERY_RESULT_BACKEND = "cache+memory://"

celery_eager_env = os.environ.get("CELERY_TASK_ALWAYS_EAGER")
if celery_eager_env is None:
    CELERY_TASK_ALWAYS_EAGER = DEBUG
else:
    CELERY_TASK_ALWAYS_EAGER = celery_eager_env == "1"

CELERY_TASK_EAGER_PROPAGATES = True

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "0.0.0.0,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "accounts",
    "polls",
    "billing",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vox_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vox_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if DATABASE_URL:
    DATABASES = {"default": _database_config_from_url(DATABASE_URL)}
elif os.environ.get("DJANGO_ENV") == "production":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_DB,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,
        }
    }
elif os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if os.environ.get("DJANGO_ENV") == "production":
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# Security best practices
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
X_FRAME_OPTIONS = "DENY"

# Enforce HTTPS in production
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_REFERRER_POLICY = "same-origin"

# DRF Spectacular settings for modular API docs
SPECTACULAR_SETTINGS = {
    "TITLE": "Vox Poll API",
    "DESCRIPTION": "Online poll system backend with modular, production-ready APIs.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
