# Generated by Django 5.2.6 on 2025-09-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_poll_question_structure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="choice",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="choice",
            name="poll",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="polls.poll",
            ),
        ),
    ]
